version: "3.8"
services:
  stream-api:
    image: tamken97/stream-api
    build:
      args:
        NODE_ENV: production
    environment:
      - NODE_ENV=production
    deploy:
      x-aws-autoscaling:
        min: 1
        max: 20 #required
        cpu: 85
        # mem: - mutualy exlusive with cpu
  nginx:
    image: tamken97/stream-api-nginx
    logging:
      options:
        awslogs-datetime-pattern: "NGINX"

x-aws-logs_retention: 10
x-aws-cloudformation:
  Resources:
    WebappTCP80TargetGroup:
      Properties:
        HealthCheckPath: /health
        Matcher:
          HttpCode: 200-499
networks:
  default:
volumes:
  db:
