version: "3.3"
services:
  stream-api:
    image: nginx-api
    build:
      context: ./
    restart: unless-stopped
    env_file:
      - ./.env
    volumes:
      - /usr/src/app/node_modules
    networks:
      - backend

  nginx:
    build:
      dockerfile: dockerfile
      context: nginx
    restart: always
    ports:
      - "80:80"
    networks:
      - backend
networks:
  backend:
    driver: bridge
