version: "3.8"
services:
  stream-api:
    build:
      context: ./
      dockerfile: dockerfile
    restart: unless-stopped
    env_file:
      - ./.env
    volumes:
      - /usr/src/app/node_modules

  nginx:
    build:
      context: nginx
      dockerfile: dockerfile
    restart: always
    ports:
      - "80:80"
