version: "3.3"
services:
  express-app:
    build:
      context: .
      args:
        NODE_ENV: production
    depends_on:
      - mongo
    environment:
      - NODE_ENV=production
  mongo:
    image: mongo
    container_name: "mongo"
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - "./db/mongodb:/data/db"
    ports:
      - 27017:27017
volumes:
  db:
